### ISSUE TITLE
Ancestral_DNA_12.5%_Cutoff

### ISSUE THREAD

**Issue by JNDX1** [jjvanantwerp/Automated-ASR#3]
Dear author, I have run the script and got some results. Compared to the directory of testing you given, it is found that a file named "Ancestral_DNA_12.5%_Cutoff" is not generated. Also, there are no fiugres generated. for example,files named Confidences.png ,SHaLRT_Confidences.png and UFB_Confidences.png.I would appreciate your kind help.

**Comment by jjvanantwerp** [comment]
I'm glad it ran, partially. There are likely two separate problems. The failure to generate figures is an issue with importing the MatPlotLib python library. This is an optional part of the code as these figures can also be generated using the .csv files for confidence data and a program such as Excel.
The failure of generating the ancestral DNA library is more concerning. Do you have a saved terminal output that you can share with me? It should have generated an error code of some kind.
________________________________
From: JNDX1 ***@***.***>
Sent: Sunday, November 6, 2022 11:23 AM
To: jjvanantwerp/Automated-ASR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jjvanantwerp/Automated-ASR] Ancestral_DNA_12.5%_Cutoff (Issue #3)


Dear author, I have run the script and got some results. Compared to the directory of testing you given, it is found that a file named "Ancestral_DNA_12.5%_Cutoff" is not generated. Also, there are no fiugres generated. for example,files named Confidences.png ,SHaLRT_Confidences.png and UFB_Confidences.png.I would appreciate your kind help.

**Comment by jjvanantwerp** [comment]
No update for several months - assumed resolved.
